### ISSUE TITLE
Does this ever change from false?

### ISSUE THREAD

**Issue by iolloyd** [stevef1uk/cassuservice#1]
https://github.com/stevef1uk/cassuservice/blob/e10baedcfc91abd76ecf466adb6f2b69ff87904a/parser/fsm_match_funcs.go#L15

**Comment by stevef1uk** [comment]
Good question. An implementation decision I made was to have the FSM action handling functions return false unless there was a need for the main FSM to look for another match for the same line. For clarity I probably should have made all these functions return true as there is only one that returns false and update the FSM function execution logic to look for false rather than true. 
To answer your question there is no reason for the function to return true as implemented.
